### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mmkim1210** [Hua-Zhou/MultiResponseVarianceComponentModels.jl#6]
- [ ] Rename package to MRVCModels.jl and register package
- [ ] Implement Fisher scoring algorithms, which can be faster and get more accurate estimates in some cases
- [ ] Make inference by information matrix faster (e.g. avoid or reduce `storages_nd_nd` alloc if possible)
- [ ] Handle $\boldsymbol{\Omega} = \sum_{i=1}^{m} \boldsymbol{\Gamma}_i * \boldsymbol{V}_i$, where $*$ is Khatri-Rao product of $d \times d$ partition matrices. Also handle different sets of covariates. Statistical model in [this paper](https://doi.org/10.1093/bioinformatics/bts474) is subsumed under this case. 
- [x] Implement missing response model for `MRTVCModel` → not possible
- [x] Implement EM algorithm for `MRTVCModel`
- [ ] Eigenvalue decomposition for single variance component case
- [ ] Simplify computation for `V[end] = I`
- [ ] Implement simulation function
- [ ] GLMM
- [ ] Low rank updates
- [ ] Make output look more aesthetically pleasing (e.g. `parse.jl`)
